[package]
name = "bokeh-lib"
description = ""
version = {workspace = true}
edition = {workspace = true}
license = {workspace = true}
repository = {workspace = true}

[lib]
crate-type = ["lib"]

[dependencies]
ndarray = "0.15.6"

[dev-dependencies]
approx = {version = "0.5.1"}
